export const ADD1E = {
  scores: {
    str: "ADD1E.scores.str.long",
    int: "ADD1E.scores.int.long",
    dex: "ADD1E.scores.dex.long",
    wis: "ADD1E.scores.wis.long",
    con: "ADD1E.scores.con.long",
    cha: "ADD1E.scores.cha.long",
    com: "ADD1E.scores.com.long"
  },
  roll_type: {
    result: "=",
    above: "≥",
    below: "≤"
  },
  saves_short: {
    death: "ADD1E.saves.death.short",
    wand: "ADD1E.saves.wand.short",
    paralysis: "ADD1E.saves.paralysis.short",
    breath: "ADD1E.saves.breath.short",
    spell: "ADD1E.saves.spell.short",
  },
  saves_long: {
    death: "ADD1E.saves.death.long",
    wand: "ADD1E.saves.wand.long",
    paralysis: "ADD1E.saves.paralysis.long",
    breath: "ADD1E.saves.breath.long",
    spell: "ADD1E.saves.spell.long",
  },
  armor : {
    unarmored: "ADD1E.armor.unarmored",
    light: "ADD1E.armor.light",
    heavy: "ADD1E.armor.heavy",
    shield: "ADD1E.armor.shield",
  },
  colors: {
    green: "ADD1E.colors.green",
    red: "ADD1E.colors.red",
    yellow: "ADD1E.colors.yellow",
    purple: "ADD1E.colors.purple",
    blue: "ADD1E.colors.blue",
    orange: "ADD1E.colors.orange",
    white: "ADD1E.colors.white"
  },
  languages: [
    "--Human Languages--",
    "Common (Oeridian)",
    "Common (Flan)",
    "Common (Sueloise)",
    "Common (Baklunish)",
    "Lawful",
    "Chaotic",
    "Neutral",
    "Good",
    "Evil",
    "Druidic",
    "Baklunish",
    "Ancient Baklunish",
    "Baklunish, Low",
    "Baklunish, Ekbir",
    "Baklunish, Ket",
    "Baklunish, Tusmit",
    "Baklunish, Ulagha (Ull)",
    "Baklunish, Osfaradd (Zeif)",
    "Baklunish, Ordai (Nomads)",
    "Baklunish, Paynim",
    "Flan",
    "Oeridian",
    "Old Oeridian",
    "Ferral",
    "Velondi",
    "Keolandish",
    "Sueloise",
    "Fruz (The Cold Tongue)",
    "Nyrondese",
    "Olman",
    "Ralat",
    "Rhopan (Rhenee)",
    "Tzigane",
    "Touv",
    "Ur-Flan",
    "--Demihuman Languages--",
    "Dwarvish (Dwur)",
    "Dwarvish - Mountain",
    "Dwarvish - Hill",
    "Elvish (Olve)",
    "Elvish - High",
    "Elvish - Sylvan",
    "Elvish - Grugach",
    "Elvish - Drow",
    "Elvish - Lendorian",
    "Gnomish (Nonniz)",
    "Gnomish, Deep (Svirfneblin)"
    "Halflingish (Hobniz)",
    "--Humanoid/Non-Human Languages--",
    "Beastfolk",
    "Bugbear",
    "Derrosh",
    "Doppelgänger",
    "Dragon",
    "Gargoyle",
    "Gnoll",
    "Goblin",
    "Harpy",
    "Hobgoblin",
    "Kech",
    "Kobold",
    "Lizard Man",
    "Medusa",
    "Minotaur",
    "Ogre",
    "Orcish (Heuroz)",
    "Pixie",
    "Tlaman",
    "Undercommon",
    "Silent Undercommon/Drow Sign Language"
  ],
  tags: {
    melee: "ADD1E.items.Melee",
    missile: "ADD1E.items.Missile",
    slow: "ADD1E.items.Slow",
    twohanded: "ADD1E.items.TwoHanded",
    blunt: "ADD1E.items.Blunt",
    brace: "ADD1E.items.Brace",
    splash: "ADD1E.items.Splash",
    reload: "ADD1E.items.Reload",
    charge: "ADD1E.items.Charge",
    pierce: "ADD1E.items.Pierce"
  },
  tag_images: {
    melee: "/systems/add1e/assets/melee.png",
    missile: "/systems/add1e/assets/missile.png",
    slow: "/systems/add1e/assets/slow.png",
    twohanded: "/systems/add1e/assets/twohanded.png",
    blunt: "/systems/add1e/assets/blunt.png",
    brace: "/systems/add1e/assets/brace.png",
    splash: "/systems/add1e/assets/splash.png",
    reload: "/systems/add1e/assets/reload.png",
    charge: "/systems/add1e/assets/charge.png",
  },
  monster_saves: {
    0: {
      d: 14,
      w: 15,
      p: 16,
      b: 17,
      s: 18
    },
    1: {
      d: 12,
      w: 13,
      p: 14,
      b: 15,
      s: 16
    },
    4: {
      d: 10,
      w: 11,
      p: 12,
      b: 13,
      s: 14
    },
    7: {
      d: 8,
      w: 9,
      p: 10,
      b: 10,
      s: 12
    },
    10: {
      d: 6,
      w: 7,
      p: 8,
      b: 8,
      s: 10
    },
    13: {
      d: 4,
      w: 5,
      p: 6,
      b: 5,
      s: 8
    },
    16: {
      d: 2,
      w: 3,
      p: 4,
      b: 3,
      s: 6
    },
    19: {
      d: 2,
      w: 2,
      p: 2,
      b: 2,
      s: 4
    },
    22: {
      d: 2,
      w: 2,
      p: 2,
      b: 2,
      s: 2
    },
  },
  monster_thac0: {
    0: 20,
    1: 19,
    2: 18,
    3: 17,
    4: 16,
    5: 15,
    6: 14,
    7: 13,
    9: 12,
    10: 11,
    12: 10,
    14: 9,
    16: 8,
    18: 7,
    20: 6,
    22: 5
  }
};
